services:
  remix-app:
    build: ./remix-app/
    image: remix-app
    ports:
      - "3000:3000"
    networks:
      - my_network
  dotnetapp:
    build: ./DotNetApp/
    image: dotnetapp
    ports:
      - "8080:8080"
    environment:
      - DB_CONNECTION_STRING="Server=postgres;Database=MyDatabase;User Id=myuser;Password=mypassword;Port=5432;"
    depends_on:
      - postgres
    command: > 
      sh -c "dotnet ef core database update && dotnet ef database update && dotnet watch run"
    networks:
      - my_network
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: MyDatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network
    
volumes:
  db_data:
    driver: local

networks:
  my_network:
    driver: bridge
